
# DOCKER FILE MULTISTAGE

# Build the image
FROM maven:3.6.3-openjdk-17 AS build

# Working directory
WORKDIR /app

# Copy source code
COPY pom.xml .
COPY src ./src

# Declaramos todos los ARG que vamos a pasar desde el pipeline
ARG PERFIL_ACTIVO
ARG CLOUDINARY_API_KEY
ARG CLOUDINARY_API_SECRET
ARG CLOUDINARY_CLOUD_NAME
ARG CLOUDINARY_URL
ARG DATABASE_NAME
ARG EMAIL_USERNAME
ARG EMAIL_PASSWORD
ARG GCP_BUCKET_NAME
ARG GCP_PROJECT_ID
ARG HIBERNATE_FORMAT_SQL
ARG JPA_HIBERNATE_DDL_AUTO
ARG JPA_SHOW_SQL
ARG JWT_SECRET
ARG POSTGRESQL_HOST
ARG POSTGRESQL_PORT
ARG POSTGRESQL_USER
ARG POSTGRESQL_PASSWORD
ARG SECURITY_USER_NAME
ARG SECURITY_USER_PASSWORD
ARG SPRING_SECURITY_LOG_LEVEL

# Build app
RUN mvn clean package -DskipTests

# -----------------------------------------------
# STAGE 2
FROM azul/zulu-openjdk:17.0.13-jre

# Set working dir
WORKDIR /app

# Copy jar file from the previous build stage
COPY --from=build /app/target/*.jar app.jar

# Convertimos cada ARG en ENV para el contenedor
ENV SPRING_PROFILES_ACTIVE=${PERFIL_ACTIVO} \
    CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY} \
    CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET} \
    CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME} \
    CLOUDINARY_URL=${CLOUDINARY_URL} \
    DATABASE_NAME=${DATABASE_NAME} \
    EMAIL_USERNAME=${EMAIL_USERNAME} \
    EMAIL_PASSWORD=${EMAIL_PASSWORD} \
    GCP_BUCKET_NAME=${GCP_BUCKET_NAME} \
    GCP_PROJECT_ID=${GCP_PROJECT_ID} \
    HIBERNATE_FORMAT_SQL=${HIBERNATE_FORMAT_SQL} \
    JPA_HIBERNATE_DDL_AUTO=${JPA_HIBERNATE_DDL_AUTO} \
    JPA_SHOW_SQL=${JPA_SHOW_SQL} \
    JWT_SECRET=${JWT_SECRET} \
    POSTGRESQL_HOST=${POSTGRESQL_HOST} \
    POSTGRESQL_PORT=${POSTGRESQL_PORT} \
    POSTGRESQL_USER=${POSTGRESQL_USER} \
    POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD} \
    SECURITY_USER_NAME=${SECURITY_USER_NAME} \
    SECURITY_USER_PASSWORD=${SECURITY_USER_PASSWORD} \
    SPRING_SECURITY_LOG_LEVEL=${SPRING_SECURITY_LOG_LEVEL}

# Expose port
EXPOSE 8080

# Run jar file
ENTRYPOINT ["java", "-jar", "app.jar"]