spring.application.name=timesnp_back


# Config logging level
# Print all logs from Spring Security package
logging.level.org.springframework.security=${SPRING_SECURITY_LOG_LEVEL:TRACE}

# Import application prod properties by default in cas not specified
spring.config.import=application-prod.properties
spring.profiles.active=${PERFIL_ACTIVO:prod}
